routes/web.php
<?php

use App\Http\Controllers\ComponentController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\TypeProposals;
use App\Http\Livewire\Roles;

use App\Http\Controllers\UsulanKegiatanController;
use App\Http\Controllers\KegiatanKelitbanganController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AbstraksiKajianController;
use App\Http\Controllers\RekomendasiHasilKelitbanganController;
use App\Http\Controllers\DataPenelitianController;
use App\Http\Controllers\RtlController;
use App\Http\Controllers\UserInputController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\ActivityMasterController;
use App\Http\Controllers\ActivitySubMasterController;
use App\Http\Controllers\SectorController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified', 'role:admin,bidang,perangkat'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');


    // Usulan Kegiatan

    Route::group(['prefix' => 'usulan-kegiatan', 'as' => 'usulanKegiatan.'], function () {
        Route::get('/', [UsulanKegiatanController::class, 'index']);
        Route::get('/create', [UsulanKegiatanController::class, 'create'])->name('create');
        Route::get('/data', [UsulanKegiatanController::class, 'data'])->name('data');
        Route::get('/edit/{id}', [UsulanKegiatanController::class, 'edit'])->name('edit');
        Route::get('/detail/{id}', [UsulanKegiatanController::class, 'detail'])->name('detail');
        Route::post('/store', [UsulanKegiatanController::class, 'store'])->name('store');
        Route::post('/update', [UsulanKegiatanController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [UsulanKegiatanController::class, 'delete'])->name('delete');
    });

    // Kegiatan Kelitbangan

    Route::group(['prefix' => 'kegiatan-kelitbangan', 'as' => 'kegiatanKelitbangan.'], function () {
        Route::get('/', [KegiatanKelitbanganController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/data', [KegiatanKelitbanganController::class, 'data'])->name('data')->middleware(['role:admin,bidang']);
        Route::get('/create/{id?}', [KegiatanKelitbanganController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::get('/edit/{id}', [KegiatanKelitbanganController::class, 'edit'])->name('edit')->middleware(['role:admin,bidang']);
        Route::get('/detail/{id}', [KegiatanKelitbanganController::class, 'detail'])->name('detail')->middleware(['role:admin,bidang']);
        Route::post('/store', [KegiatanKelitbanganController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::get('/redirect/{id}', [KegiatanKelitbanganController::class, 'redirectForm'])->name('redirect')->middleware(['role:admin,bidang']);
        Route::post('/update', [KegiatanKelitbanganController::class, 'update'])->name('update')->middleware(['role:admin,bidang']);
    });

    // Data Penelitian

    Route::get('data-penelitian/abstraksi-kajian/data', [AbstraksiKajianController::class, 'data'])->middleware(['role:admin,bidang']);
    Route::resource('data-penelitian/abstraksi-kajian', AbstraksiKajianController::class)->middleware(['role:admin,bidang']);

    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/{id}/detail', [RekomendasiHasilKelitbanganController::class,'show'])->middleware(['role:admin,bidang,perangkat']);
    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/data', [RekomendasiHasilKelitbanganController::class,'data'])->middleware(['role:admin,bidang,perangkat']);
    Route::resource('data-penelitian/rekomendasi-hasil-kelitbangan', RekomendasiHasilKelitbanganController::class)->middleware(['role:admin,bidang,perangkat']);
   
    Route::group(['prefix' => 'data-penelitian', 'as' => 'dataPenelitian.'], function () {
        Route::get('/', [DataPenelitianController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/create/{type}/{id}', [DataPenelitianController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::post('/store', [DataPenelitianController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::post('/store_hasil', [DataPenelitianController::class, 'store_hasil'])->name('store_hasil')->middleware(['role:admin,bidang']);
    });

    // rtl

    Route::get('rtl/data', [RtlController::class, 'data'])->middleware(['role:admin,perangkat']);
    Route::resource('rtl', RtlController::class)->middleware(['role:admin,perangkat']);

    Route::get('master/user/data', [UserController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/user/{id}/delete', [UserController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/user', UserController::class)->middleware(['role:admin']);


    // Master survey

    Route::get('master/question/data', [QuestionController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/question/{id}/delete', [QuestionController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/question', QuestionController::class)->middleware(['role:admin']);


    Route::get('master/survey/data', [SurveyController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/survey/{id}/delete', [SurveyController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/survey', SurveyController::class)->middleware(['role:admin']);

    Route::get('user-input/data/{id?}', [UserInputController::class, 'data'])->middleware(['role:perangkat,admin']);
    Route::resource('user-input', UserInputController::class)->middleware(['role:perangkat,admin']);
    Route::get('user-input/detail/{id?}', [UserInputController::class, 'index'])->middleware(['role:perangkat,admin']);


    Route::get('master/activity/data', [ActivityMasterController::class,'data'])->middleware(['role:admin']);
    Route::get('master/activity/{id}/delete', [ActivityMasterController::class,'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity', ActivityMasterController::class)->middleware(['role:admin']);

    Route::get('master/activity-sub/data', [ActivitySubMasterController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/activity-sub/{id}/delete', [ActivitySubMasterController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity-sub', ActivitySubMasterController::class)->middleware(['role:admin']);

    Route::get('master/sector/data', [SectorController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/sector/{id}/delete', [SectorController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/sector', SectorController::class)->middleware(['role:admin']);


    Route::get('json/{type}/{id?}', [UsulanKegiatanController::class, 'jsonActivity']);



    // Route::get('/components', function () {
    //     return view('layouts.components');
    // })->name('components');

    // Master
    // Route::get('master/jenis-usulan-kelitbangan', TypeProposals::class);
    // Route::get('master/role', Roles::class);

});

resources/views/navigation-menu.blade.php
<div x-data="{ open: false }">
  <!-- Navigation -->
  <nav class="bg-white shadow flex xl:hidden flex-wrap items-center fixed top-0 inset-x-0 px-5 sm:px-12 h-[72px] w-full z-base">
    <button id="sidebarToggler" class="hover:text-primary border-0 outline-none duration-300 ease-in-out" type="button" data-target="#sidebarLeft" data-icons="#toggleIconsButton">
      <div id="toggleIconsButton" class="hamburger pl-0">
        <span class="hamburger-items"></span>
        <span class="hamburger-items"></span>
        <span class="hamburger-items"></span>
      </div>
    </button>
    <a class="outline-none m-auto relative select-none" href="{{ route('dashboard') }}">
      <div class="h-9 w-auto">
        <img class="h-full w-auto" src="{{ url('./img/e-intan.png') }}" alt="Brand Logo">
      </div>
    </a>
    <div>
      <div class="flex items-center relative select-none">
        <x-ui.form.dropdown align="right">
          <x-slot name="trigger">
            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
            <button type="button" class="bg-transparent shadow-none outline-none h-[72px]" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="rounded-full overflow-hidden relative h-11 w-11">
                <img class="bg-no-repeat bg-center bg-cover object-cover h-full w-full" src="{{ url('./img/wp-profiles.jpg') }}" alt="Images (Profiles)">
              </div>
            </button>
            @else
            <button type="button" class="bg-transparent shadow-none outline-none h-[72px]" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="rounded-full overflow-hidden relative h-11 w-11">
                <img class="bg-no-repeat bg-center bg-cover object-cover h-full w-full" src="{{ url('./img/wp-profiles.jpg') }}" alt="Images (Profiles)">
              </div>
            </button>
            @endif
          </x-slot>

          <x-slot name="content">
            <div class="py-2.5 px-5 pb-3">
              <div class="flex flex-col text-black font-inter text-sm font-semibold tracking-tight py-2 mb-1">
                {{ __('Pengaturan Akun') }}
              </div>

              <x-ui.form.dropdown-link href="{{ route('profile.show') }}">{{ __('Profil Pengguna') }}</x-ui.form.dropdown-link>

              @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
              <x-ui.form.dropdown-link href="{{ route('api-tokens.index') }}">{{ __('API Tokens') }}</x-ui.form.dropdown-link>
              @endif

              <div class="border-t border-gray-200 my-2"></div>

              <form method="POST" action="{{ route('logout') }}">
                @csrf
                <x-ui.form.dropdown-link href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
                  {{ __('LogOut') }}
                </x-ui.form.dropdown-link>
              </form>
            </div>
          </x-slot>
        </x-ui.form.dropdown>
      </div>
    </div>
  </nav>

  <!-- Sidebar -->
  <section id="sidebarLeft" class="bg-primary flex flex-col flex-wrap fixed inset-y-0 left-0 pt-[72px] xl:pt-0 h-full w-[340px] duration-500 transform xl:transform-none -translate-x-full xl:translate-x-0 z-normal">
    <div class="sidebar-scroll flex flex-col overflow-y-auto pt-8 xl:pt-14 px-6 pb-0 h-full">
      <!-- Brand Logo -->
      <div class="hidden xl:flex px-3.5 mb-10 select-none h-[52px] w-auto">
        <img class="h-full w-auto" src="{{ url('./img/e-intan-white.png') }}" alt="Brand Logo">
      </div>

      <!-- Menu -->
      <div class="flex flex-col justify-between h-full">
        <ul class="flex flex-col list-none pl-0 mb-0 h-auto">
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal ring-0 outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('dashboard') }}">
              <x-heroicon-s-view-grid class=" fill-current mr-2 h-6 w-6" />
              {{ __('Dashboard') }}
            </a>
          </li>

          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('usulanKegiatan.') }}">
              <x-heroicon-s-check-circle class="fill-current mr-2 h-6 w-6" />
              {{ __('Usulan Kegiatan') }}
            </a>
          </li>

          @if (Auth::user()->role->name=='admin' || Auth::user()->role->name=='bidang')
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('kegiatanKelitbangan.') }}">
              <x-heroicon-s-clipboard-list class="fill-current mr-2 h-6 w-6" />
              {{ __('Kegiatan Kelitbangan') }}
            </a>
          </li>
          <li class="flex flex-col outline-none relative mb-1">
            <a class="sidebar-dropdown hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="#" data-toggle="sidebar-submenu">
              <x-heroicon-s-archive class="fill-current mr-2 h-6 w-6" />
              {{ __('Data Penelitian') }}
              <span class="flex items-center justify-center absolute inset-y-auto left-auto right-3.5 h-6 w-6">
                <x-heroicon-o-chevron-down class="parent-icons stroke-current h-[18px] w-[18px]" />
              </span>
            </a>

            <!-- Sub Menu Data Penelitian -->
            <ul class="sidebar-submenu sidebar-submenu-collapse flex-col border-l-2 border-solid border-gray-300 border-opacity-30 list-none pl-2 my-4 ml-[26px] h-auto" data-collapse="sidebar-submenu-collapse">
              <li class="flex flex-col outline-none relative mb-1">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('abstraksi-kajian.index') }}">
                  {{ __('Abstraksi Kajian') }}
                </a>
              </li>
              <li class="flex flex-col outline-none relative mb-0">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('rekomendasi-hasil-kelitbangan.index') }}">
                  {{ __('Rekomendasi Hasil') }}
                </a>
              </li>
            </ul>
          </li>
          @endif

          @if (Auth::user()->role->name=='perangkat')
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('rekomendasi-hasil-kelitbangan.index') }}">
              <x-heroicon-s-archive class="fill-current mr-2 h-6 w-6" />
              {{ __('Rekomendasi Hasil') }}
            </a>
          </li>
          @endif

          @if (Auth::user()->role->name=='admin' || Auth::user()->role->name=='perangkat')
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('rtl.index') }}">
              <x-heroicon-s-color-swatch class="fill-current mr-2 h-6 w-6" />
              {{ __('RTL') }}
            </a>
          </li>
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('user-input.create') }}">
              <x-heroicon-s-chat-alt-2 class="fill-current mr-2 h-6 w-6" />
              {{ __('Saran & Masukkan') }}
            </a>
          </li>
          @endif

          @if (Auth::user()->role->name=='admin')
          <li class="flex flex-col outline-none relative mb-1">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('user-input.index') }}">
              <x-heroicon-s-annotation class="fill-current mr-2 h-6 w-6" />
              {{ __('Hasil Saran & Masukkan') }}
            </a>
          </li>

          <li class="flex flex-col outline-none relative mb-1">
            <a class="sidebar-dropdown hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="#" data-toggle="sidebar-submenu">
              <x-heroicon-s-database class="fill-current mr-2 h-6 w-6" />
              {{ __('Master Data') }}
              <span class="flex items-center justify-center absolute inset-y-auto left-auto right-3.5 h-6 w-6">
                <x-heroicon-o-chevron-down class="parent-icons stroke-current h-[18px] w-[18px]" />
              </span>
            </a>

            <!-- Sub Menu Data Penelitian -->
            <ul class="sidebar-submenu sidebar-submenu-collapse flex-col border-l-2 border-solid border-gray-300 border-opacity-30 list-none pl-2 my-4 ml-[26px] h-auto" data-collapse="sidebar-submenu-collapse">
              <li class="flex flex-col outline-none relative mb-0">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('sector.index') }}">
                  {{ __('Bidang') }}
                </a>
              </li>
              <li class="flex flex-col outline-none relative mb-0">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('question.index') }}">
                  {{ __('Pertanyaan') }}
                </a>
              </li>
              <li class="flex flex-col outline-none relative mb-1">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('survey.index') }}">
                  {{ __('Survei') }}
                </a>
              </li>
              <li class="flex flex-col outline-none relative mb-1">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('activity.index') }}">
                  {{ __('Aktivitas') }}
                </a>
              </li>
              <li class="flex flex-col outline-none relative mb-1">
                <a class="hover:bg-lightgreen-2 flex items-center rounded-[5px] font-inter text-white text-xs font-normal ring-0 outline-none relative py-2.5 pl-4 pr-0 duration-500 ease-in-out" href="{{ route('activity-sub.index') }}">
                  {{ __('Sub Aktivitas') }}
                </a>
              </li>
            </ul>
          </li>
          <li class="flex flex-col outline-none relative mb-0">
            <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('user.index') }}">
              <x-heroicon-s-cog class="fill-current mr-2 h-6 w-6" />
              {{ __('Pengguna Aplikasi') }}
            </a>
          </li>
          @endif
        </ul>

        <!-- LogOut -->
        <form method="POST" action="{{ route('logout') }}">
          @csrf
          <ul class="flex flex-col list-none pt-[152px] pl-0 pb-8 mb-0">
            <li class="flex flex-col outline-none relative mb-2">
              <a class="hover:bg-lightgreen-2 flex items-center rounded-lg font-inter text-white text-base font-normal outline-none relative py-4 px-4 duration-500 ease-in-out" href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
                <x-heroicon-o-logout class="stroke-current mr-2 h-6 w-6" />
                {{ __('LogOut') }}
              </a>
            </li>
          </ul>
        </form>
      </div>
    </div>
  </section>
</div>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>