routes/web.php
<?php

use App\Http\Controllers\ComponentController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\TypeProposals;
use App\Http\Livewire\Roles;

use App\Http\Controllers\UsulanKegiatanController;
use App\Http\Controllers\KegiatanKelitbanganController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AbstraksiKajianController;
use App\Http\Controllers\RekomendasiHasilKelitbanganController;
use App\Http\Controllers\DataPenelitianController;
use App\Http\Controllers\RtlController;
use App\Http\Controllers\UserInputController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\ActivityMasterController;
use App\Http\Controllers\ActivitySubMasterController;
use App\Http\Controllers\SectorController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified', 'role:admin,bidang,perangkat'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');


    // Usulan Kegiatan

    Route::group(['prefix' => 'usulan-kegiatan', 'as' => 'usulanKegiatan.'], function () {
        Route::get('/', [UsulanKegiatanController::class, 'index']);
        Route::get('/create', [UsulanKegiatanController::class, 'create'])->name('create');
        Route::get('/data', [UsulanKegiatanController::class, 'data'])->name('data');
        Route::get('/edit/{id}', [UsulanKegiatanController::class, 'edit'])->name('edit');
        Route::get('/detail/{id}', [UsulanKegiatanController::class, 'detail'])->name('detail');
        Route::post('/store', [UsulanKegiatanController::class, 'store'])->name('store');
        Route::post('/update', [UsulanKegiatanController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [UsulanKegiatanController::class, 'delete'])->name('delete');
    });

    // Kegiatan Kelitbangan

    Route::group(['prefix' => 'kegiatan-kelitbangan', 'as' => 'kegiatanKelitbangan.'], function () {
        Route::get('/', [KegiatanKelitbanganController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/data', [KegiatanKelitbanganController::class, 'data'])->name('data')->middleware(['role:admin,bidang']);
        Route::get('/create/{id?}', [KegiatanKelitbanganController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::get('/edit/{id}', [KegiatanKelitbanganController::class, 'edit'])->name('edit')->middleware(['role:admin,bidang']);
        Route::get('/detail/{id}', [KegiatanKelitbanganController::class, 'detail'])->name('detail')->middleware(['role:admin,bidang']);
        Route::post('/store', [KegiatanKelitbanganController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::get('/redirect/{id}', [KegiatanKelitbanganController::class, 'redirectForm'])->name('redirect')->middleware(['role:admin,bidang']);
        Route::post('/update', [KegiatanKelitbanganController::class, 'update'])->name('update')->middleware(['role:admin,bidang']);
    });

    // Data Penelitian

    Route::get('data-penelitian/abstraksi-kajian/data', [AbstraksiKajianController::class, 'data'])->middleware(['role:admin,bidang']);
    Route::resource('data-penelitian/abstraksi-kajian', AbstraksiKajianController::class)->middleware(['role:admin,bidang']);

    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/{id}/detail', [RekomendasiHasilKelitbanganController::class,'show'])->middleware(['role:admin,bidang,perangkat']);
    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/data', [RekomendasiHasilKelitbanganController::class,'data'])->middleware(['role:admin,bidang,perangkat']);
    Route::resource('data-penelitian/rekomendasi-hasil-kelitbangan', RekomendasiHasilKelitbanganController::class)->middleware(['role:admin,bidang,perangkat']);
   
    Route::group(['prefix' => 'data-penelitian', 'as' => 'dataPenelitian.'], function () {
        Route::get('/', [DataPenelitianController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/create/{type}/{id}', [DataPenelitianController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::post('/store', [DataPenelitianController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::post('/store_hasil', [DataPenelitianController::class, 'store_hasil'])->name('store_hasil')->middleware(['role:admin,bidang']);
    });

    // rtl

    Route::get('rtl/data', [RtlController::class, 'data'])->middleware(['role:admin,perangkat']);
    Route::resource('rtl', RtlController::class)->middleware(['role:admin,perangkat']);

    Route::get('master/user/data', [UserController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/user/{id}/delete', [UserController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/user', UserController::class)->middleware(['role:admin']);


    // Master survey

    Route::get('master/question/data', [QuestionController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/question/{id}/delete', [QuestionController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/question', QuestionController::class)->middleware(['role:admin']);


    Route::get('master/survey/data', [SurveyController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/survey/{id}/delete', [SurveyController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/survey', SurveyController::class)->middleware(['role:admin']);

    Route::get('user-input/data/{id?}', [UserInputController::class, 'data'])->middleware(['role:perangkat,admin']);
    Route::resource('user-input', UserInputController::class)->middleware(['role:perangkat,admin']);
    Route::get('user-input/detail/{id?}', [UserInputController::class, 'index'])->middleware(['role:perangkat,admin']);


    Route::get('master/activity/data', [ActivityMasterController::class,'data'])->middleware(['role:admin']);
    Route::get('master/activity/{id}/delete', [ActivityMasterController::class,'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity', ActivityMasterController::class)->middleware(['role:admin']);

    Route::get('master/activity-sub/data', [ActivitySubMasterController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/activity-sub/{id}/delete', [ActivitySubMasterController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity-sub', ActivitySubMasterController::class)->middleware(['role:admin']);

    Route::get('master/sector/data', [SectorController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/sector/{id}/delete', [SectorController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/sector', SectorController::class)->middleware(['role:admin']);


    Route::get('json/{type}/{id?}', [UsulanKegiatanController::class, 'jsonActivity']);



    // Route::get('/components', function () {
    //     return view('layouts.components');
    // })->name('components');

    // Master
    // Route::get('master/jenis-usulan-kelitbangan', TypeProposals::class);
    // Route::get('master/role', Roles::class);

});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'question',
        'category',
        'order',
    ];

    public function user_input_question()
    {
        return $this->hasMany(User_input_question::class);
    }

    public function survey_question()
    {
        return $this->hasMany(Survey_question::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\Datatables;
use App\Models\Question;


class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('modul/question.index');

        //
    }

    public function data()
    {
        //
        $questions = Question::query();
        return Datatables::of($questions)->make();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('modul/question.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(
            $request, 
            [
                'order' => 'required',
                'question' => 'required'
            ],
            [
                'order.required' => 'Masukan Nomor Urut wajib diisi.',
                'question.required' => 'Masukan Pertanyaan wajib diisi.'
            ],
        );
        Question::create($request->except('_token'));
        return redirect()->route('question.index')
                        ->with('success','Perntanyaan berhasil dibuat.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $question = Question::findOrFail($id);

        $dataGet = [
            'question' => $question,
        ];

        return view('modul/question.edit', $dataGet);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate(
            $request, 
            [
                'order' => 'required',
                'question' => 'required'
            ],
            [
                'order.required' => 'Masukan Nomor Urut wajib diisi.',
                'question.required' => 'Masukan Pertanyaan wajib diisi.'
            ],
        );
        Question::find($id)->update($request->except('_token'));
        return redirect()->route('question.index')
                        ->with('success','Perntanyaan berhasil diperbarui.');
                        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $question = Question::findOrFail($id)->delete();

        return redirect()->route('question.index')
                        ->with('success','Pertanyaan berhasil dihapus.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/modul/question/create.blade.php
<x-app-layout>
  <x-slot name="header">
    <div class="mb-4 lg:mb-0">
      <h4 class="text-black font-poppins text-2xl font-semibold tracking-tight antialiased">{{ __('Pertanyaan') }}</h4>
    </div>
    <div class="flex items-center justify-between">
      <div class="flex whitespace-nowrap sm:whitespace-[none] overflow-x-auto sm:overflow-hidden pb-3 sm:pb-0 xl:mr-6 w-full">
        <nav class="" aria-label="breadcrumb">
          <ul class="flex text-gray-200 font-light leading-none">
            <li class="">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('question.index') }}">{{ __('Pertanyaan') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="text-gray-400 font-normal outline-none duration-300 ease-in-out" aria-current="page">{{ __('Tambah') }}</li>
          </ul>
        </nav>
      </div>
      @include('layouts.header.action')
    </div>
  </x-slot>

  <div class="bg-white flex flex-col rounded pt-5 px-[22px] pb-8">
    <div class="flex items-center justify-between pb-4 mb-2">
      <h3 class="text-black font-inter text-lg font-semibold capitalize tracking-tight">Tambah Data : </h3>
      <p class="text-gray-400 font-inter text-base font-normal capitalize tracking-tight">{{ __('Pertanyaan') }}</p>
    </div>
    <div class="flex flex-col relative">

      @if ($errors->any())
      <div class="bg-red-100 rounded-lg text-red-600 font-inter tracking-tight relative py-4 pl-5 pr-10 duration-300 ease-in-out" role="alert">
        <h3 class="text-base font-medium mb-5"><strong>Ups!</strong>, Ada beberapa data yang belum dilengkapi...</h3>
        <ul class="flex flex-col list-none pl-0">
          @foreach ($errors->all() as $error)
          <li class="text-sm font-normal mb-3 sm:mb-0 last:mb-0">{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif

      <div class="pt-8">
        <form method="POST" action="{{ route('question.store') }}">
          @csrf

          <div class="grid grid-cols-12 gap-5 select-none">
            <div class="col-span-12 sm:col-span-6">
              <div class="relative">
                <x-ui.form.label for="category" title="Kategori Pertanyaan" />
                <select id="category" class="custom-select custom-select2 rounded-lg shadow-none" name="category" required>
                  <option selected>Pilih Kategori Pertanyaan : </option>
                  <option value="Layanan Umum">Layanan Umum</option>
                  <option value="Layanan Teknis">Layanan Teknis</option>
                  <option value="Kemampuan SDM Petugas">Kemampuan SDM Petugas</option>
                </select>
              </div>
            </div>
            <div class="col-span-12 sm:col-span-6">
              <div class="relative">
                <x-ui.form.label for="order" title="Nomor Urut Pertanyaan" />
                <x-ui.form.input id="order" type="number" name="order" size="md" parent="" maxlength="120" aria-placeholder="Masukan urutan pertanyaan" placeholder="Masukan urutan pertanyaan" required />
              </div>
            </div>

            <div class="col-span-12">
              <div class="relative">
                <x-ui.form.label for="question" title="Pertanyaan" />
                <x-ui.form.textarea id="question" type="text" name="question" size="md" rows="5" maxlength="255" aria-placeholder="Masukan Pertanyaan" placeholder="Masukan Pertanyaan" value="" message="" required />
              </div>
            </div>
            <div class="col-span-12">
              <div class="relative">
                <x-ui.form.button background="primary" variant="default" size="md" rounded="base" title="Simpan" icon-l="heroicon-o-save" icon-type="fill" type="submit" />
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
</x-app-layout>

resources/views/modul/question/edit.blade.php
<x-app-layout>
  <x-slot name="header">
    <div class="mb-4 lg:mb-0">
      <h4 class="text-black font-poppins text-2xl font-semibold tracking-tight antialiased">{{ __('Bidang') }}</h4>
    </div>
    <div class="flex items-center justify-between">
      <div class="flex whitespace-nowrap sm:whitespace-[none] overflow-x-auto sm:overflow-hidden pb-3 sm:pb-0 xl:mr-6 w-full">
        <nav class="" aria-label="breadcrumb">
          <ul class="flex text-gray-200 font-light leading-none">
            <li class="">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('sector.index') }}">{{ __('Bidang') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="text-gray-400 font-normal outline-none duration-300 ease-in-out" aria-current="page">{{ __('Edit') }}</li>
          </ul>
        </nav>
      </div>
      @include('layouts.header.action')
    </div>
  </x-slot>

  <div class="bg-white flex flex-col rounded pt-5 px-[22px] pb-8">
    <div class="flex items-center justify-between pb-4 mb-2">
      <h3 class="text-black font-inter text-lg font-semibold capitalize tracking-tight">Tambah Data : </h3>
      <p class="text-gray-400 font-inter text-base font-normal capitalize tracking-tight">{{ __('Bidang') }}</p>
    </div>
    <div class="flex flex-col relative">

      @if ($errors->any())
      <div class="bg-red-100 rounded-lg text-red-600 font-inter tracking-tight relative py-4 pl-5 pr-10 duration-300 ease-in-out" role="alert">
        <h3 class="text-base font-medium mb-5"><strong>Ups!</strong>, Ada beberapa data yang belum dilengkapi...</h3>
        <ul class="flex flex-col list-none pl-0">
          @foreach ($errors->all() as $error)
          <li class="text-sm font-normal mb-3 sm:mb-0 last:mb-0">{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif

      <div class="pt-8">
        <form method="POST" action="{{ route('question.update',$question->id) }}">
          @csrf
          @method('PUT')

          <div class="grid grid-cols-12 gap-5 select-none">
            <div class="col-span-12 sm:col-span-6">
              <div class="relative">
                <x-ui.form.label for="category" title="Kategori Pertanyaan" />
                <select id="category" class="custom-select custom-select2 rounded-lg shadow-none" name="category" required>
                  <option selected>Pilih Kategori Pertanyaan : </option>
                  <option value="Layanan Umum" @if ($question->category=="Layanan Umum")
                    selected="selected"
                    @endif>Layanan Umum</option>
                  <option value="Layanan Teknis" @if ($question->category=="Layanan Teknis")
                    selected="selected"
                    @endif>Layanan Teknis</option>
                  <option value="Kemampuan SDM Petugas" @if ($question->category=="Kemampuan SDM Petugas")
                    selected="selected"
                    @endif>Kemampuan SDM Petugas</option>
                </select>
              </div>
            </div>
            <div class="col-span-12 sm:col-span-6">
              <div class="relative">
                <x-ui.form.label for="order" title="Nomor Urut Pertanyaan" />
                <x-ui.form.input id="order" type="number" name="order" size="md" parent="" maxlength="120" aria-placeholder="Masukan urutan pertanyaan" placeholder="Masukan urutan pertanyaan" value="{{ $question->order }}" required />
              </div>
            </div>
            <div class="col-span-12">
              <div class="relative">
                <x-ui.form.label for="question" title="Pertanyaan" />
                <x-ui.form.textarea id="question" type="text" name="question" size="md" rows="5" maxlength="255" aria-placeholder="Masukan Pertanyaan" placeholder="Masukan Pertanyaan" message="{{ $question->question }}" required />
              </div>
            </div>

            <div class="col-span-12">
              <div class="relative">
                <x-ui.form.button background="primary" variant="default" size="md" rounded="base" title="Simpan" icon-l="heroicon-o-save" icon-type="fill" type="submit" />
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</x-app-layout>

resources/views/modul/question/index.blade.php
<x-app-layout>
  <x-slot name="header">
    <div class="mb-4 lg:mb-0">
      <h4 class="text-black font-poppins text-2xl font-semibold tracking-tight antialiased">{{ __('Pertanyaan') }}</h4>
    </div>
    <div class="flex items-center justify-between">
      <div class="flex whitespace-nowrap sm:whitespace-[none] overflow-x-auto sm:overflow-hidden pb-3 sm:pb-0 xl:mr-6 w-full">
        <nav class="" aria-label="breadcrumb">
          <ul class="flex text-gray-200 font-light leading-none">
            <li class="">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="text-gray-400 font-normal outline-none duration-300 ease-in-out" aria-current="page">{{ __('Pertanyaan') }}</li>
          </ul>
        </nav>
      </div>
      @include('layouts.header.action')
    </div>
  </x-slot>

  <div class="bg-white flex flex-col rounded pt-5 px-[22px] pb-8">
    <div class="flex items-center justify-between pb-4 mb-2">
      <h3 class="text-black font-inter text-lg font-semibold capitalize tracking-tight">{{ __('Data Pertanyaan') }}</h3>
      <a href="{{ route('question.create') }}">
        <x-ui.form.button background="primary" variant="default" size="base" rounded="base" title="Tambah Data" type="button" />
      </a>
    </div>
    <div class="flex flex-col relative w-full">
      @if ($message = Session::get('success'))
      <div class="bg-green-100 rounded-lg leading-normal text-green-700 font-inter tracking-tight relative py-3 pl-4 pr-10 duration-300 ease-in-out" role="alert">
        <p>{{ $message }}</p>
      </div>
      @endif

      <div class="pt-8 overflow-hidden">
        <table id="tableQuestion" class="table-data whitespace-nowrap xl:whitespace-normal">
          <thead>
            <tr>
              <td scope="col" width="0%">No</td>
              <td scope="col">Pertanyaan</td>
              <td scope="col" width="0%">Kategori</td>
              <td scope="col" width="0%"></td>
            </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!-- JavaScript (Pertanyaan) -->
  <script>
    $(() => {
      $('#tableQuestion').DataTable({
        processing: true,
        serverSide: true,
        scrollX: true,
        ajax: '{{ url("master/question/data") }}',
        columns: [{
            "data": "order",
            "className": "first text-center"
          },
          {
            "data": "question"
          },
          {
            "data": "category"
          },
          {
            "data": "id",
            "className": "last"
          },
        ],
        order: [
          [1, 'asc']
        ],
        "columnDefs": [{
            "targets": 0,
            orderable: false,
          },
          {
            "targets": 2,
            orderable: false,
            "render": (data, type, row, meta) => {
              if (data == 'Layanan Umum') {
                return `
                  <div class="flex whitespace-nowrap">
                    <x-ui.form.button background="status-secondary" variant="status" size="base" rounded="pill" title="${ data }" type="button" />
                  </div>
                `;
              } else if (data == 'Layanan Teknis') {
                return `
                  <div class="flex whitespace-nowrap">
                    <x-ui.form.button background="status-danger" variant="status" size="base" rounded="pill" title="${ data }" type="button" />
                  </div>
                `;
              } else {
                return `
                  <div class="flex whitespace-nowrap">
                    <x-ui.form.button background="status-success" variant="status" size="base" rounded="pill" title="${ data }" type="button" />
                  </div>
                `;
              }
            }
          },
          {
            "targets": 3,
            "data": "id",
            "render": (data, type, row, meta) => {
              var questionEdit = "{{ url('master/question') }}" + "/" + data + "/edit";
              var questionDelete = "{{ url('master/question') }}/" + data + "/delete";

              return `
                <x-ui.form.dropdown align="drop-left">
                  <x-slot name="trigger">
                    <button class="hover:text-green flex flex-col bg-transparent border-0 outline-none py-[9px] px-0 ml-3 mr-3 w-auto" type="button">
                      <x-heroicon-o-dots-horizontal class="fill-current h-5 w-5 duration-300 ease-in-out" />
                    </button> 
                  </x-slot>

                  <x-slot name="content">
                    <div class="py-2.5 px-5 pr-8">
                      <x-ui.form.dropdown-link href="` + questionEdit + `">
                        <x-heroicon-s-pencil-alt class="fill-current mr-2 h-[18px] w-[18px]" />
                        {{ __('Perbarui') }}
                      </x-ui.form.dropdown-link>
                      <x-ui.form.dropdown-link class="text-danger hover:text-danger focus:text-danger" href="javascript:void(0);" onclick="return questionDelete('` + questionDelete + `')">
                        <x-heroicon-s-trash class="fill-current mr-2 h-[18px] w-[18px]" />
                        {{ __('Hapus') }}
                      </x-ui.form.dropdown-link>
                    </div>
                  </x-slot>
                </x-ui.form.dropdown>
              `;
            }
          },
        ]
      });
    });

    // Alert Delete (Pertanyaan)
    let questionDelete = (getURL) => {
      swal({
        title: "Apakah Anda sudah yakin?",
        text: "Setelah dihapus, Anda tidak dapat memulihkan Usulan Kegiatan ini!",
        icon: "warning",
        buttons: ["Batal", "Hapus"],
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          // swal("File anda telah berhasil dihapus!", {
          //   icon: "success",
          //   button: {
          //     text: "Oke",
          //   },
          // });

          $.ajax({
            type: 'GET',
            url: getURL,
            // data: data,
            success: (data) => {
              swal("File anda telah berhasil dihapus!", {
                icon: "success",
                button: {
                  text: "Oke",
                },
              });
              setTimeout(() => {
                location.reload()
              }, 2000);
            },
            error: (data) => {
              swal("File anda tidak berhasil dihapus! ada masalah pada server", {
                icon: "warning",
                button: {
                  text: "Oke",
                },
              });
            }
          });
        }
      });
    };
  </script>
</x-app-layout>