routes/web.php
<?php

use App\Http\Controllers\ComponentController;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\TypeProposals;
use App\Http\Livewire\Roles;

use App\Http\Controllers\UsulanKegiatanController;
use App\Http\Controllers\KegiatanKelitbanganController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AbstraksiKajianController;
use App\Http\Controllers\RekomendasiHasilKelitbanganController;
use App\Http\Controllers\DataPenelitianController;
use App\Http\Controllers\RtlController;
use App\Http\Controllers\UserInputController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\ActivityMasterController;
use App\Http\Controllers\ActivitySubMasterController;
use App\Http\Controllers\SectorController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified', 'role:admin,bidang,perangkat'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');


    // Usulan Kegiatan

    Route::group(['prefix' => 'usulan-kegiatan', 'as' => 'usulanKegiatan.'], function () {
        Route::get('/', [UsulanKegiatanController::class, 'index']);
        Route::get('/create', [UsulanKegiatanController::class, 'create'])->name('create');
        Route::get('/data', [UsulanKegiatanController::class, 'data'])->name('data');
        Route::get('/edit/{id}', [UsulanKegiatanController::class, 'edit'])->name('edit');
        Route::get('/detail/{id}', [UsulanKegiatanController::class, 'detail'])->name('detail');
        Route::post('/store', [UsulanKegiatanController::class, 'store'])->name('store');
        Route::post('/update', [UsulanKegiatanController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [UsulanKegiatanController::class, 'delete'])->name('delete');
    });

    // Kegiatan Kelitbangan

    Route::group(['prefix' => 'kegiatan-kelitbangan', 'as' => 'kegiatanKelitbangan.'], function () {
        Route::get('/', [KegiatanKelitbanganController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/data', [KegiatanKelitbanganController::class, 'data'])->name('data')->middleware(['role:admin,bidang']);
        Route::get('/create/{id?}', [KegiatanKelitbanganController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::get('/edit/{id}', [KegiatanKelitbanganController::class, 'edit'])->name('edit')->middleware(['role:admin,bidang']);
        Route::get('/detail/{id}', [KegiatanKelitbanganController::class, 'detail'])->name('detail')->middleware(['role:admin,bidang']);
        Route::post('/store', [KegiatanKelitbanganController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::get('/redirect/{id}', [KegiatanKelitbanganController::class, 'redirectForm'])->name('redirect')->middleware(['role:admin,bidang']);
        Route::post('/update', [KegiatanKelitbanganController::class, 'update'])->name('update')->middleware(['role:admin,bidang']);
    });

    // Data Penelitian

    Route::get('data-penelitian/abstraksi-kajian/data', [AbstraksiKajianController::class, 'data'])->middleware(['role:admin,bidang']);
    Route::resource('data-penelitian/abstraksi-kajian', AbstraksiKajianController::class)->middleware(['role:admin,bidang']);

    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/{id}/detail', [RekomendasiHasilKelitbanganController::class,'show'])->middleware(['role:admin,bidang,perangkat']);
    Route::get('data-penelitian/rekomendasi-hasil-kelitbangan/data', [RekomendasiHasilKelitbanganController::class,'data'])->middleware(['role:admin,bidang,perangkat']);
    Route::resource('data-penelitian/rekomendasi-hasil-kelitbangan', RekomendasiHasilKelitbanganController::class)->middleware(['role:admin,bidang,perangkat']);
   
    Route::group(['prefix' => 'data-penelitian', 'as' => 'dataPenelitian.'], function () {
        Route::get('/', [DataPenelitianController::class, 'index'])->middleware(['role:admin,bidang']);
        Route::get('/create/{type}/{id}', [DataPenelitianController::class, 'create'])->name('create')->middleware(['role:admin,bidang']);
        Route::post('/store', [DataPenelitianController::class, 'store'])->name('store')->middleware(['role:admin,bidang']);
        Route::post('/store_hasil', [DataPenelitianController::class, 'store_hasil'])->name('store_hasil')->middleware(['role:admin,bidang']);
    });

    // rtl

    Route::get('rtl/data', [RtlController::class, 'data'])->middleware(['role:admin,perangkat']);
    Route::resource('rtl', RtlController::class)->middleware(['role:admin,perangkat']);

    Route::get('master/user/data', [UserController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/user/{id}/delete', [UserController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/user', UserController::class)->middleware(['role:admin']);


    // Master survey

    Route::get('master/question/data', [QuestionController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/question/{id}/delete', [QuestionController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/question', QuestionController::class)->middleware(['role:admin']);


    Route::get('master/survey/data', [SurveyController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/survey/{id}/delete', [SurveyController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/survey', SurveyController::class)->middleware(['role:admin']);

    Route::get('user-input/data/{id?}', [UserInputController::class, 'data'])->middleware(['role:perangkat,admin']);
    Route::resource('user-input', UserInputController::class)->middleware(['role:perangkat,admin']);
    Route::get('user-input/detail/{id?}', [UserInputController::class, 'index'])->middleware(['role:perangkat,admin']);


    Route::get('master/activity/data', [ActivityMasterController::class,'data'])->middleware(['role:admin']);
    Route::get('master/activity/{id}/delete', [ActivityMasterController::class,'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity', ActivityMasterController::class)->middleware(['role:admin']);

    Route::get('master/activity-sub/data', [ActivitySubMasterController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/activity-sub/{id}/delete', [ActivitySubMasterController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/activity-sub', ActivitySubMasterController::class)->middleware(['role:admin']);

    Route::get('master/sector/data', [SectorController::class, 'data'])->middleware(['role:admin']);
    Route::get('master/sector/{id}/delete', [SectorController::class, 'destroy'])->middleware(['role:admin']);
    Route::resource('master/sector', SectorController::class)->middleware(['role:admin']);


    Route::get('json/{type}/{id?}', [UsulanKegiatanController::class, 'jsonActivity']);



    // Route::get('/components', function () {
    //     return view('layouts.components');
    // })->name('components');

    // Master
    // Route::get('master/jenis-usulan-kelitbangan', TypeProposals::class);
    // Route::get('master/role', Roles::class);

});

app/Http/Controllers/UsulanKegiatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\User;
use App\Models\Type_proposal;
use App\Models\Activity_proposal;
use App\Models\Activity_master;
use App\Models\Activity_sub_master;

use Yajra\DataTables\Datatables;
use DB;
use Auth;

class UsulanKegiatanController extends Controller
{
    //


    public function index(Request $request)
    {
        $role = Role::where('name','perangkat')->first();
        $data['users'] = User::where('role_id',$role->id)->get();
        $data['type_proposals'] = Type_proposal::get();
        $data['years'] = Activity_proposal::selectRaw("DISTINCT(proposed_year) as year")->get();

        
        $filter = "";
        if($request->filter_date_usulan){
            $data['date'] = $request->filter_date_usulan;
            if($filter=="") $filter .= '?date='.$request->filter_date_usulan;
            else $filter .= '&date='.$request->filter_date_usulan;
        }else{
            $data['date'] = "";
        }
        
        if($request->user_id){
            $data['user_id'] = $request->user_id;
            if($filter=="") $filter .= '?user_id='.implode(',',$request->user_id);
            else $filter .= '&user_id='.implode(',',$request->user_id);
        }else{
            $data['user_id'] = [];
        }

        if($request->proposed_year){
            $data['proposed_year'] = $request->proposed_year;
            if($filter=="") $filter .= '?proposed_year='.implode(',',$request->proposed_year);
            else $filter .= '&proposed_year='.implode(',',$request->proposed_year);
        }else{
            $data['proposed_year'] = [];
        }

        if($request->type_proposal_id){
            $data['type_proposal_id'] = $request->type_proposal_id;
            if($filter=="") $filter .= '?type_proposal_id='.implode(',',$request->type_proposal_id);
            else $filter .= '&type_proposal_id='.implode(',',$request->type_proposal_id);
        }else{
            $data['type_proposal_id'] = [];
        }

        $data['filter'] = $filter;

        return view('modul/usulan-kegiatan.index',$data);
    }

    public function data(Request $request)
    {

        $activityProposals = Activity_proposal::with('type_proposal','user');
        if($request->proposed_year){
            $activityProposals->whereIn('proposed_year',explode(',',$request->proposed_year));
        }

        if(Auth::user()->role->name=="perangkat"){
            $activityProposals->whereIn('user_id',explode(',',Auth::user()->id));
        }else{
            if($request->user_id){
                $activityProposals->whereIn('user_id',explode(',',$request->user_id));
            }
        }

        if($request->type_proposal_id){
            $activityProposals->whereIn('type_proposal_id',explode(',',$request->type_proposal_id));
        }

        return Datatables::of($activityProposals)->make();

    }

    public function jsonActivity(Request $request,$type,$id=null)
    {
        if($type=="activity"){
            $data = Activity_master::where('name', 'like', '%'.$request->q.'%')->get();
            $json = [];
            foreach($data as $rec){
                if($request->checked==$rec['id']){
                    $json[] = [
                        'id'=>$rec['id'],
                        'text'=>$rec['name'],
                        'selected'=>true
                    ];
                }else{
                    $json[] = [
                        'id'=>$rec['id'],
                        'text'=>$rec['name'],
                    ];
                }

            }
        }else{
            $data = Activity_sub_master::where('name', 'like', '%'.$request->q.'%')->where('activity_master_id',$id)->get();
            $json = [];
            foreach($data as $rec){
                if($request->checked==$rec['id']){
                    $json[] = [
                        'id'=>$rec['id'],
                        'text'=>$rec['name'],
                        'selected'=>true
                    ];
                }else{
                    $json[] = [
                        'id'=>$rec['id'],
                        'text'=>$rec['name'],
                    ];
                }
            }

        }

        $return['results']  = $json; 
        return response()->json($return);
    }

    public function create()
    {

        if(Auth::user()->role->name!='perangkat'){
            $roles = Role::with('user')->where('name','perangkat')->first();
            $user = $roles->user;
        }else{
            $user = User::where('id',Auth::user()->id)->get();
        }
        $typeProposal = Type_proposal::get();

        $dataGet = [
            'users' => $user,
            'typeProposals' => $typeProposal
        ];
        return view('modul/usulan-kegiatan.create', $dataGet);
    }


    public function store(Request $request)
    {

        $this->validate(
            $request, 
            [
                'type_proposal_title' => 'required',
                'problem' => 'required',
               
            ],
            [
                'type_proposal_title.required' => 'Masukan Judul wajib diisi.',
                'problem.required' => 'Masukan Permasalahan wajib diisi.',
                
            ],
        );
        Activity_proposal::create($request->all());
         
        return redirect()->route('usulanKegiatan.')
                        ->with('success','Usulan kegiatan berhasil dibuat.');
    }


    public function update(Request $request)
    {

        $this->validate(
            $request, 
            [
                'type_proposal_title' => 'required',
                'problem' => 'required'
            ],
            [
                'type_proposal_title.required' => 'Masukan Judul wajib diisi.',
                'problem.required' => 'Masukan Permasalahan wajib diisi.'
            ],
        );
        Activity_proposal::where('id',$request->id)->update($request->except('_token'));
         
        return redirect()->route('usulanKegiatan.')
                        ->with('success','Usulan kegiatan berhasil diperbaharui.');
    }

    public function delete($id)
    {
        $activityProposal = Activity_proposal::with('type_proposal')->find($id);
        if(!$activityProposal)  return redirect()->route('usulanKegiatan.')
        ->with('danger','Usulan kegiatan tidak ditemukan.');

        Activity_proposal::where('id',$id)->delete();
        return redirect()->route('usulanKegiatan.')
        ->with('success','Usulan kegiatan berhasil dihapus.');

    }

    

    public function edit($id)
    {
        $activityProposal = Activity_proposal::with('type_proposal')->find($id);
        $typeProposal = Type_proposal::get();

        if(Auth::user()->role->name!='perangkat'){
            $roles = Role::with('user')->where('name','perangkat')->first();
            $user = $roles->user;
        }else{
            $user = User::where('id',Auth::user()->id)->get();
        }

        $dataGet = [
            'activityProposal' => $activityProposal,
            'users' => $user,
            'typeProposals' => $typeProposal
        ];

        if($activityProposal->status=='canceled') return redirect()->route('usulanKegiatan.');
        return view('modul/usulan-kegiatan.edit', $dataGet);
    }

    public function detail($id)
    {
        $activityProposal = Activity_proposal::with('type_proposal')->find($id);

        $dataGet = [
            'activityProposal' => $activityProposal
        ];
        return view('modul/usulan-kegiatan.detail', $dataGet);
        
        # code...
    }
}

resources/views/modul/usulan-kegiatan/detail.blade.php
<x-app-layout>
  <x-slot name="header">
    <div class="mb-4 lg:mb-0">
      <h4 class="text-black font-poppins text-2xl font-semibold tracking-tight antialiased">{{ __('Usulan Kegiatan') }}</h4>
    </div>
    <div class="flex items-center">
      <div class="flex whitespace-nowrap sm:whitespace-[none] overflow-x-auto sm:overflow-hidden pb-3 sm:pb-0 xl:mr-6 w-full">
        <nav class="" aria-label="breadcrumb">
          <ul class="flex items-center text-gray-200 font-light leading-5">
            <li class="w-min">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="w-min">
              <a class="text-primary font-normal outline-none duration-300 ease-in-out" href="{{ route('usulanKegiatan.') }}">{{ __('Usulan Kegiatan') }}</a>
            </li>
            <li class="mx-2">/</li>
            <li class="text-gray-400 font-normal outline-none duration-300 ease-in-out" aria-current="page">{{ __('Detail') }}</li>
          </ul>
        </nav>
      </div>
      @include('layouts.header.action')
    </div>
  </x-slot>

  <div class="bg-white flex flex-col rounded pt-5 px-[22px] pb-8">
    <div class="flex items-start justify-between pb-4 mb-2">
      <div class="flex flex-col items-start">
        <h3 class="text-black font-inter text-lg font-semibold capitalize tracking-tight">{{ $activityProposal->type_proposal_title }}</h3>
        <p class="text-gray-400 font-inter text-base font-normal capitalize tracking-tight mb-1">{{ $activityProposal->type_proposal->name }}</p>
      </div>
      @if ($activityProposal->status!='canceled' && $activityProposal->status!='process')
      <a href="javascript:void(0);" onclick="return detailUsulanDelete({{ $activityProposal->id }})">
        <x-ui.form.button background="danger" variant="default" size="base" rounded="base" title="Hapus" icon-l="heroicon-s-trash" icon-type="fill" type="button" />
      </a>
      @endif
      @if ($activityProposal->status=='process')
      <a href="{{ route('kegiatanKelitbangan.redirect',$activityProposal->id) }}">
        <x-ui.form.button background="primary" variant="default" size="base" rounded="base" title="Lihat Kegiatan" type="button" />
      </a>
      @endif
    </div>
    <div class="flex flex-col relative">

      @if ($errors->any())
      <div class="bg-red-100 rounded-lg text-red-600 font-inter tracking-tight relative py-4 pl-5 pr-10 duration-300 ease-in-out" role="alert">
        <h3 class="text-base font-medium mb-5"><strong>Whoops!</strong> There were some problems with your input.</h3>
        <ul class="flex flex-col list-none pl-0">
          @foreach ($errors->all() as $error)
          <li class="text-sm font-normal mb-3 sm:mb-0 last:mb-0">{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif

      <div class=" pt-8">
        <dl class="font-inter">
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Nama Perangkat Daerah
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {{ $activityProposal->user->name }}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Permasalahan
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {!! $activityProposal->problem !!}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Tujuan
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {!! $activityProposal->aim !!}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Output
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {!! $activityProposal->output !!}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Outcome
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {!! $activityProposal->outcome !!}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Tahun Usulan
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              {{ $activityProposal->proposed_year }}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex text-black text-sm font-semibold">
              Perkiraan Anggaran
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-2 sm:mt-0">
              <span class="hidden sm:flex sm:mr-3">:</span>
              Rp.{{ number_format($activityProposal->estimated_budget) }}
            </dd>
          </div>
          <div class="sm:grid sm:grid-cols-3 py-4 px-0">
            <dt class="flex items-center text-black text-sm font-semibold">
              Status & Proses Selanjutnya
              <span class="flex sm:hidden ml-2 mr-2.5">:</span>
            </dt>
            <dd class="flex sm:col-span-2 text-sm text-gray-800 font-normal mt-3.5 sm:mt-0">
              <span class="hidden sm:flex sm:items-center sm:mr-3">:</span>
              <div class="flex border border-gray-200 rounded-lg overflow-y-hidden overflow-x-auto py-3.5 px-3.5 w-max max-w-full">
                <div class="flex items-center">
                  @if ($activityProposal->status=='draft')
                  <x-ui.form.button background="status-secondary" variant="status" size="base" rounded="pill" title="{{ ucfirst($activityProposal->status) }}" type="button" />
                  @elseif ($activityProposal->status=='canceled')
                  <x-ui.form.button background="status-danger" variant="status" size="base" rounded="pill" title="{{ ucfirst($activityProposal->status) }}" type="button" />
                  @else
                  <x-ui.form.button background="status-success" variant="status" size="base" rounded="pill" title="{{ ucfirst($activityProposal->status) }}" type="button" />
                  @endif
                </div>
                @if ($activityProposal->status!='canceled' && $activityProposal->status!='process')
                <div class="flex ml-3">
                  <div class="mr-2.5">
                    <a class=" whitespace-nowrap" href="{{ route('usulanKegiatan.edit',$activityProposal->id) }}">
                      <x-ui.form.button background="dark" variant="default" size="base" rounded="base" title="Perbarui Usulan" type="button" />
                    </a>
                  </div>
                  <a class=" whitespace-nowrap" href="{{ route('kegiatanKelitbangan.create',$activityProposal->id) }}">
                    <x-ui.form.button background="primary" variant="default" size="base" rounded="base" title="Buat Usulan Kegiatan" type="button" />
                  </a>
                </div>
                @endif
              </div>
            </dd>
          </div>
        </dl>
      </div>
    </div>
  </div>

  <!-- Detail Alert Delete (Ususlan Kegiatan) -->
  <script>
    let detailUsulanDelete = (getId) => {
      swal({
        title: "Apakah Anda sudah yakin?",
        text: "Setelah dihapus, Anda tidak dapat memulihkan Usulan Kegiatan ini!",
        icon: "warning",
        buttons: ["Batal", "Hapus"],
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          swal("File anda telah berhasil dihapus!", {
            icon: "success",
            button: {
              text: "Oke",
            },
          });

          // $.ajax({
          //   type: 'POST',
          //   url: 'url',
          //   data: data,
          //   success: (data) => {
          //     swal("File anda telah berhasil dihapus!", {
          //       icon: "success",
          //       button: {
          //         text: "Oke",
          //       },
          //     });
          //   },
          //   error: (data) => {
          //     swal("File anda tidak berhasil dihapus! ada masalah pada server", {
          //       icon: "warning",
          //       button: {
          //         text: "Oke",
          //       },
          //     });
          //   }
          // });
        }
      });
    };
  </script>
</x-app-layout>